# 02 - Tiền xử lý dữ liệu (Preprocessing)

Mục tiêu: Làm sạch, chuẩn hóa, và lưu dữ liệu đã xử lý cho EDA và Visualization.

## Các bước dự kiến
- Hợp nhất dữ liệu từ nhiều nguồn
- Làm sạch giá/đánh giá/số lượng bán
- Chuẩn hóa định dạng thời gian
- Lưu dữ liệu vào data/processed

In [ ]:
# import libraries
import pandas as pd
from pathlib import Path

In [ ]:
# merge data


# merge_dir = Path(r"D:\Vscode\Self\Data Science\Book Notes\Data Visualization\Lab\Lab1\Lab1---Data-Visualization-\data\raw\merge")
# out_file = Path(r"D:\Vscode\Self\Data Science\Book Notes\Data Visualization\Lab\Lab1\Lab1---Data-Visualization-\data\raw\raw_merged.csv")

# csv_files = sorted(merge_dir.glob("*.csv"))
# df = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
# df.to_csv(out_file, index=False)

# out_file

WindowsPath('D:/Vscode/Self/Data Science/Book Notes/Data Visualization/Lab/Lab1/Lab1---Data-Visualization-/data/raw/raw_merged.csv')

In [3]:
# Read data and general obverse
df = pd.read_csv('../data/raw/raw_merged.csv')

df.describe(include='all')

,ID,Giá (tỷ đồng),Giá đã tăng 1 năm qua (%),Diện tích,Số phòng tắm,Số phòng ngủ,Số tầng,Có nội thất,Mặt tiền(m),Đường vào(m),...,Loại Tin,ngày crawl,blocked,source_url,address,legal,raw_price,raw_area,page_title,_source_file
count,2.988700e+04,29422.000000,29035.000000,29887.000000,19503.000000,20283.000000,15914.000000,29900.000000,16622.000000,15347.000000,...,29887,29900,29900,29900,29887,26982,29887,29887,29900,29900
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,29900,1,16104,5834,182,1398,1868,16021,998
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tin thường,2026-02-22 08:10:05.448701,False,https://batdongsan.com.vn/ban-dat-duong-pham-v...,"Westgate, Đường Tân Túc, Thị trấn Tân Túc, Huy...",Sổ đỏ/ Sổ hồng,10 tỷ,80 m²,Đất hiếm 80m2 mặt tiền Phạm Văn Chiêu khúc kin...,scraped_results_p251.csv
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29491,1,29900,483,673,21984,754,1116,483,30
mean,4.434302e+07,15.212461,15.507804,105.940324,3.642414,3.717251,3.372188,0.480702,7.126050,9.634613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.973040e+06,32.174719,16.629102,99.703324,3.050663,3.340558,1.416800,0.499636,7.341507,7.646189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,8.974785e+06,0.003300,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.445620e+07,4.780000,6.100000,57.000000,2.000000,2.000000,2.000000,0.000000,4.000000,5.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.494199e+07,7.500000,11.800000,77.000000,3.000000,3.000000,3.000000,0.000000,5.000000,8.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.511298e+07,12.500000,19.700000,113.000000,5.000000,4.000000,4.000000,1.000000,8.000000,12.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.516533e+07,985.000000,272.700000,997.000000,80.000000,128.000000,22.000000,1.000000,450.000000,200.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29900 entries, 0 to 29899
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         29887 non-null  float64
 1   Giá (tỷ đồng)              29422 non-null  float64
 2   Giá đã tăng 1 năm qua (%)  29035 non-null  float64
 3   Diện tích                  29887 non-null  float64
 4   Số phòng tắm               19503 non-null  float64
 5   Số phòng ngủ               20283 non-null  float64
 6   Số tầng                    15914 non-null  float64
 7   Có nội thất                29900 non-null  int64
 8   Mặt tiền(m)                16622 non-null  float64
 9   Đường vào(m)               15347 non-null  float64
 10  Hướng nhà                  7250 non-null   str
 11  Đường                      28554 non-null  str
 12  Phường                     29486 non-null  str
 13  Quận                       29887 non-null  str
 14  Thành Phố                  29883 non-null  str
 15  Có sổ hồng                 29900 non-null  int64
 16  Có xác thực                29900 non-null  int64
 17  Ngày đăng                  29887 non-null  str
 18  Ngày hết hạn               29887 non-null  str
 19  Loại Tin                   29887 non-null  str
 20  ngày crawl                 29900 non-null  str
 21  blocked                    29900 non-null  bool
 22  source_url                 29900 non-null  str
 23  address                    29887 non-null  str
 24  legal                      26982 non-null  str
 25  raw_price                  29887 non-null  str
 26  raw_area                   29887 non-null  str
 27  page_title                 29900 non-null  str
 28  _source_file               29900 non-null  str
dtypes: bool(1), float64(9), int64(3), str(16)
memory usage: 6.4 MB

In [6]:
df.head()

,ID,Giá (tỷ đồng),Giá đã tăng 1 năm qua (%),Diện tích,Số phòng tắm,Số phòng ngủ,Số tầng,Có nội thất,Mặt tiền(m),Đường vào(m),...,Loại Tin,ngày crawl,blocked,source_url,address,legal,raw_price,raw_area,page_title,_source_file
0,43386973.0,24.50,33.0,220.0,3.0,4.0,3.0,1,10.0,12.0,...,Tin thường,2026-02-22 08:10:05.448701,False,https://batdongsan.com.vn/ban-nha-biet-thu-lie...,"Dự án Sol Villas, Đường Nguyễn Thị Định, Phườn...",Sổ đỏ/ Sổ hồng,"24,5 tỷ",220 m²,"Bán biệt thự song lập Sol Villas Quận 2, giỏ h...",scraped_results_p251.csv
1,45165326.0,46.00,19.1,187.5,NaN,NaN,NaN,0,10.0,NaN,...,Tin thường,2026-02-22 08:10:11.883281,False,https://batdongsan.com.vn/ban-nha-biet-thu-lie...,"Victoria Village, Phường Thạnh Mỹ Lợi, Quận 2,...",Sổ đỏ/ Sổ hồng,46 tỷ,"187,5 m²","Bán BT Victoria Village, 46 tỷ, 187.5m2, Tây B...",scraped_results_p251.csv
2,41296667.0,25.50,33.0,220.0,3.0,4.0,3.0,1,10.0,12.0,...,Tin thường,2026-02-22 08:10:17.602817,False,https://batdongsan.com.vn/ban-nha-biet-thu-lie...,"Dự án Sol Villas, Đường Nguyễn Thị Định, Phườn...",Sổ đỏ/ Sổ hồng.,"25,5 tỷ",220 m²,PhoDong Village Quận 2 bán căn biệt thự song l...,scraped_results_p251.csv
3,45056216.0,9.99,0.0,80.0,NaN,NaN,NaN,0,4.0,NaN,...,Tin thường,2026-02-22 08:10:20.572576,False,https://batdongsan.com.vn/ban-dat-duong-pham-v...,"Đường Phạm Văn Chiêu, Phường 14, Quận Gò Vấp, ...",Sổ đỏ/ Sổ hồng,"9,99 tỷ",80 m²,Đất hiếm 80m2 mặt tiền Phạm Văn Chiêu khúc kin...,scraped_results_p251.csv
4,45106540.0,9.50,11.1,62.7,4.0,3.0,4.0,1,5.0,NaN,...,Tin thường,2026-02-22 08:10:23.242561,False,https://batdongsan.com.vn/ban-nha-rieng-phuong...,"Phường Phú Thuận, Quận 7, Hồ Chí Minh",Sổ đỏ/ Sổ hồng,"9,5 tỷ","62,7 m²","Bán nhà quận 7, nhà mới khu cao tầng Lacasa Ho...",scraped_results_p251.csv